version: '3'

services:
    mongo-db:
        image: mongo:6.0
        container_name: mongo-db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
            - MONGO_INITDB_DATABASE=${DB_NAME}
        ports:
            - '27017:27017'
        volumes:
            - db:/data/db
        networks:
            - payment-service

    server:
        restart: always
        container_name: payment-service-backend
        image: payment-service-backend:latest
        build:
            context: .
            dockerfile: server/docker/Dockerfile
        expose:
            - 8000
        depends_on:
            - mongo_db
        networks:
            - payment-network

    nginx:
        restart: always
        container_name: payment-service-nginx
        image: payment-service-nginx:latest
        build:
            context: ./nginx
            dockerfile: ./Dockerfile
        ports:
            - 80:80
        depends_on:
            - server
            - mongo_db
        networks:
            - payment-service

volumes:
    db:
        name: payment-service-db

networks:
    payment-service:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.11.0.0/16
