version: '3'

services:
    server:
        restart: always
        container_name: payment-service-backend
        image: payment-service-backend:latest
        build:
            context: .
            dockerfile: server/docker/Dockerfile
        expose:
            - 8000
        ports:
            - 8000:8000
